# Generated by Django 5.2.9 on 2026-01-13 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='lecturer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'dosen'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
